name: 'Process Pull Request'
on:
  push:
    branches:
    - 'main'
  pull_request:
    branches:
    - 'main'
jobs:
  build-and-test:
    name: 'Build And Test'
    runs-on: 'ubuntu-latest'
    timeout-minutes: 30
    steps:
    - id: 'step-0'
      name: 'checkout'
      uses: 'actions/checkout@v6.0.2'
    - id: 'step-1'
      name: 'setup jdk'
      uses: 'actions/setup-java@v5.2.0'
      with:
        java-version: '25'
        distribution: 'corretto'
        java-package: 'jdk'
        cache: 'gradle'
    - id: 'step-2'
      name: 'cache konan dir'
      uses: 'actions/cache@v5.0.4'
      with:
        path: '~/.konan/**/*'
        key: '.konan'
    - id: 'step-3'
      name: 'setup gradle'
      uses: 'gradle/actions/setup-gradle@v6.0.1'
    - id: 'step-4'
      name: 'build with gradle'
      run: './gradlew check'
      env:
        OPENCAGE_KEY: '${{ secrets.OPENCAGE_KEY }}'
